### ISSUE TITLE
Get cat-data-service setup to test continuous snapshot

### ISSUE THREAD

**Issue by mike-mcnulty** [input-output-hk/catalyst-core#606]
Need cat-data-service up and working in preprod env to test continuous snapshot feature in mobile app. Should be able to query for both mainnet and testnet wallets. 

@kukkok3 @FelipeRosa to specify work needed to be done

**Comment by jmgilman** [comment]
Still working on getting this to successfully run in dev. It's been suffering timeouts whenever it tries to perform a snapshot on mainnet. We applied some new flags to the PostgreSQL container today to see if it will help. The underlying issue is unclear, though. 

@kukkok3 has been given access to the dbsync machine and will work on testing snapshots locally to determine if the issue lies within the machine or if it's related to the SSH connection.
